# Generated by Django 3.2 on 2021-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_statuslog_logger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at UTC time'),
        ),
    ]
