# Generated by Django 3.2 on 2021-06-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_user'),
        ('invoices', '0002_auto_20210603_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
