# Generated by Django 3.2 on 2021-06-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210603_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
