# Generated by Django 3.2 on 2021-07-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='invoicereceipts/'),
        ),
    ]
