# Generated by Django 3.2 on 2021-05-07 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('style', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=25)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('warehouse', models.CharField(max_length=20)),
                ('ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('orderDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('sfmID', models.CharField(max_length=50)),
            ],
        ),
    ]
