# Generated by Django 3.2 on 2021-05-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sfmID',
            new_name='sfmId',
        ),
    ]
