# Generated by Django 3.2 on 2021-05-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_sfmid_purchase_sfmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='arrivalDate',
        ),
    ]
