# Generated by Django 3.2 on 2021-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_sfmid_purchase_sfmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='arrivalDate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaseId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
