# Generated by Django 3.2 on 2021-05-12 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_arrivaldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ordered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
