# Generated by Django 3.2 on 2021-05-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('sfmId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=25)),
                ('inStock', models.IntegerField()),
                ('arrivalDate', models.DateField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
    ]
