# Generated by Django 3.2 on 2021-06-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='arrivalDate',
            field=models.DateField(null=True),
        ),
    ]
