# Generated by Django 3.2 on 2021-05-07 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='emailAddress',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='zipCode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
