# Generated by Django 3.2 on 2021-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
