# Generated by Django 3.2 on 2021-05-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_alter_store_addressline2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(max_length=15)),
                ('saleDate', models.DateField()),
                ('orderNo', models.CharField(max_length=20)),
                ('recipientName', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=25)),
                ('design', models.CharField(max_length=50)),
                ('processing', models.CharField(max_length=1)),
                ('printed', models.CharField(max_length=1)),
                ('shipped', models.CharField(max_length=1)),
                ('sfmNotes', models.CharField(max_length=5000)),
                ('buyerName', models.CharField(max_length=50)),
                ('buyerEmail', models.CharField(max_length=50)),
                ('buyerComments', models.CharField(max_length=5000)),
                ('giftMessages', models.CharField(max_length=5000)),
                ('sku', models.CharField(max_length=20)),
                ('shipDate', models.DateTimeField(null=True)),
                ('priorityShip', models.CharField(max_length=50)),
                ('customerPaidShipping', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trackingNumber', models.CharField(max_length=30)),
                ('productAvailability', models.CharField(max_length=20)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='stores.store')),
            ],
        ),
    ]
