# Generated by Django 3.2 on 2021-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sfmId',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
