# Generated by Django 3.2 on 2021-05-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_saledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productAvailability',
        ),
    ]
