# Generated by Django 3.2 on 2021-06-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_customerpaidshipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerPaidShipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='saleDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
