# Generated by Django 3.2 on 2021-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sfmId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=25)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amountInStock', models.CharField(max_length=50)),
            ],
        ),
    ]
