# Generated by Django 3.2 on 2021-05-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210508_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amountInStock',
        ),
    ]
